# -*- coding: utf-8 -*-
"""MatematikselislemHhsaplayıci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Pr9bLEcuMnUiP3n_FMjYNdTBjTTapk5
"""

import gradio as gr

def hesapla(sayi1, sayi2, islem):
    sayi1 = float(sayi1)
    sayi2 = float(sayi2)
    if islem == "Topla":
        return sayi1 + sayi2
    elif islem == "Çıkar":
        return sayi1 - sayi2
    elif islem == "Böl":
        return sayi1 / sayi2
    elif islem == "Çarp":
        return sayi1 * sayi2
    else:
        return "Geçersiz işlem"

with gr.Interface(
    fn=hesapla,
    inputs=[
        gr.Textbox(label="Sayı 1"),
        gr.Textbox(label="Sayı 2"),
        gr.Dropdown(choices=["Topla", "Çıkar", "Böl", "Çarp"], label="İşlem Seçin"),
    ],
    outputs="text",
    title="Matematiksel İşlem Hesaplayıcı",
    description="İki sayı girin ve bir işlem seçin."
) as iface:
    iface.launch()

